#include "../../Core/ShaderLibrary/Common.hlsl"

Texture2D<float4> _Source;
RWTexture2D<float4> _Result;

SamplerState sampler_LinearClamp;

CBUFFER_START(cb)
    float4 _Size;
CBUFFER_END

#pragma kernel KMain
[numthreads(8, 8, 1)]
void KMain(uint2 groupId : SV_GroupID, uint2 groupThreadId : SV_GroupThreadID, uint2 dispatchThreadId : SV_DispatchThreadID)
{
    _Result[dispatchThreadId] = _Source.SampleLevel(sampler_LinearClamp, float2(dispatchThreadId) *_Size.zw, 0.0);
}
